version: '3'
services:

  vantage6-server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      # - ./configs/sqlite.yaml:/mnt/config.yaml
      - ./configs/postgress.yaml:/mnt/config.yaml
    command: ["/mnt/config.yaml"]

  database:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme