summary: Get OVPN configuration file

description: |
  Returns the contents of an OVPN configuration file. This configuration allows the node to connect to EduVPN. To
  access this endpoint, the node needs to be authenticated.

responses:
  200:
    description: Ok
  401:
    description: Unauthorized or missing permission

security:
  - bearerAuth: []

tags: ["Other"]
